In [2]:
import numpy as np
from sklearn import linear_model

x = np.array([1,2,3,4,5])
y = np.array([5,7, 9, 11, 13])

reg = linear_model.LinearRegression()
reg.fit(x.reshape(-1, 1), y)

reg.predict([[8]])

array([19.])

# Pickle

In [3]:
import pickle

with open('model_pickle', 'wb') as f: 
    pickle.dump(reg, f)

In [4]:
with open('model_pickle', 'rb') as f: 
    mp = pickle.load(f)

In [6]:
mp.predict([[10]])

array([23.])

# JobLib

In [9]:
import joblib

In [11]:
joblib.dump(reg, 'model_joblib')

['model_joblib']

In [12]:
mj = joblib.load('model_joblib')

In [13]:
mj.predict([[21]])

array([45.])